sudo: required

language: java
jdk:
  - openjdk11

script:
  - ./gradlew compileJava
  - ./gradlew compileTestJava
  - ./gradlew checkstyleMain
  - ./gradlew checkstyleTest
  - ./gradlew pmdMain
  - ./gradlew pmdTest
